export type Gallery = {
    id: number;
    title: string;
    date: string;
    images: string[];
};

export const galleries: Gallery[] = [
        {
            id: 1,
            title: "ADEBISI MODEL SCHOOL OPENING",
            date: "2018",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
            ],
        },
        {
            id: 2,
            title: "ADEBISI MODEL SCHOOL EXCURSION",
            date: "2019",
            images: [
                "/adebisi17.jpg",
                "/adebisi18.jpg",
                "/adebisi19.jpg",
                "/adebisi20.jpg",
                "/adebisi21.jpg",
                "/adebisi22.jpg",
                "/adebisi23.jpg",
                "/adebisi24.jpg",
                "/adebisi25.jpg",
                "/adebisi26.jpg",
                "/adebisi27.jpg",
            ],
        },
        {
            id: 3,
            title: "ADEBISI MODEL SCHOOL ILEYA FESTIVAL",
            date: "2020",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
            ],
        },
        {
            id: 4,
            title: "EARLY YEARS FACILITIES AT ADEBISI MODEL SCHOOL",
            date: "2021",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
            ],
        },
        {
            id: 5,
            title: "ADEBISI MODEL SCHOOL CHILDREN'S DAY CONCERT",
            date: "2022",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
                "/GOODBADBOY2.jpg",
                "/GOODBADBOY1.jpg",
            ],
        },
        {
            id: 6,
            title: "EARLY YEARS FACILITIES AT ADEBISI MODEL SCHOOL",
            date: "2023",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
            ],
        },
        {
            id: 7,
            title: "END OF THE YEAR ACTIVITIES",
            date: "2024",
            images: [
                "/adebisi7.jpg",
                "/adebisi8.jpg",
                "/adebisi9.jpg",
                "/adebisi10.jpg",
                "/adebisi11.jpg",
                "/adebisi12.jpg",
                "/adebisi13.jpg",
                "/adebisi14.jpg",
                "/adebisi15.jpg",
                "/adebisi16.jpg",
                "/adebisi28.jpg",
                "/adebisi29.jpg",
                "/adebisi30.jpg",
                "/adebisi31.jpg",
                "/adebisi32.jpg",
                "/adebisi33.jpg",
                "/adebisi34.jpg",
                "/adebisi35.jpg",
                "/adebisi36.jpg",
                "/adebisi37.jpg",
                "/adebisi38.jpg",
                "/adebisi39.jpg",
                "/adebisi40.jpg",
                "/adebisi41.jpg",
                "/adebisi42.jpg",
                "/adebisi43.jpg",
                "/adebisi44.jpg",
                "/adebisi45.jpg",
                "/adebisi46.jpg",
                "/adebisi47.jpg",
            ],
        },
        {
            id: 8,
            title: "END OF THE YEAR ACTIVITIES",
            date: "2025",
            images: [
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
                "/GOODBADBOY.jpg",
            ],
        },
        {
            id: 9,
            title: "ADEBISI SPORT FESTIVAL",
            date: "2025",
            images: [
                "/sport1.jpg",
                "/sport2.jpg",
                "/sport3.jpg",
                "/sport4.jpg",
                "/sport5.jpg",
                "/sport6.jpg",
                "/sport7.jpg",
                "/sport8.jpg",
                "/sport9.jpg",
                "/sport10.jpg",
                "/sport11.jpg",
                "/sport12.jpg",
                "/sport13.jpg",
                "/sport14.jpg",
                "/sport15.jpg",
                "/sport16.jpg",
                "/sport17.jpg",
                "/sport18.jpg",
                "/sport19.jpg",
                "/sport20.jpg",
                "/sport21.jpg",
                "/sport22.jpg",
                "/sport23.jpg",
                "/sport24.jpg",
                "/sport25.jpg",
                "/sport26.jpg",
                "/sport27.jpg",
                "/sport28.jpg",
                "/sport29.jpg",
                "/sport30.jpg",
                "/sport31.jpg",
                "/sport32.jpg",
                "/sport33.jpg",
                "/sport34.jpg",
                "/sport35.jpg",
                "/sport36.jpg",
                "/sport37.jpg",
                "/sport38.jpg",
                "/sport39.jpg",
                "/sport40.jpg",
                "/sport41.jpg",
                "/sport42.jpg",
            ],
        },
    ];