export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        {/* Separate layout for admin */}
        <header className="bg-blue-600 text-white p-4">
          <h1 className="text-xl font-bold">Admin Panel</h1>
        </header>
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
