export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// app/(student)/dashboard/layout.tsx
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className="bg-gray-100 min-h-screen"> */}
      <body className="bg-black">
        <div className="min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
