export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen">
        {/* You can add a sidebar/navbar just for students */}
        <div className="flex">
          <aside className="w-64 bg-white shadow-md min-h-screen p-4">
            <h2 className="font-bold text-lg">Student Dashboard</h2>
            {/* Sidebar links */}
          </aside>
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
